apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
type: Opaque
stringData:
  # O mysql sempre recebe a senha em base64
  # Senha em base64 (3g9PW9Um3Y5qiEn)
  password: M2c5UFc5VW0zWTVxaUVu
